/**
 * AI Image Stub — Panel component.
 *
 * Reference extension demonstrating the extension Panel contract.
 * Shows a simple UI with a "Generate" button that injects a placeholder
 * SVG image into the selected shape. No real AI provider integration —
 * this is a development scaffold for testing the extension pipeline.
 */
import { useState } from "react";
import type { ExtensionPanelProps } from "../registry";

const PLACEHOLDER_SVG = `data:image/svg+xml,${encodeURIComponent(
  `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 400 400">
    <rect width="400" height="400" fill="#f0f0f0"/>
    <text x="200" y="190" text-anchor="middle" font-family="system-ui" font-size="14" fill="#888">AI Image Placeholder</text>
    <text x="200" y="215" text-anchor="middle" font-family="system-ui" font-size="11" fill="#aaa">Extension stub — no real provider</text>
  </svg>`,
)}`;

const PLACEHOLDER_HTML = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { margin: 0; display: flex; align-items: center; justify-content: center; min-height: 100vh; background: #fafafa; font-family: system-ui, sans-serif; }
  .card { text-align: center; padding: 2rem; }
  img { width: 100%; max-width: 320px; border-radius: 8px; }
  p { color: #666; font-size: 0.875rem; margin-top: 1rem; }
</style></head>
<body>
  <div class="card">
    <img src="${PLACEHOLDER_SVG}" alt="AI Generated placeholder" />
    <p>Generated by AI Image Stub</p>
  </div>
</body>
</html>`;

export function AiImagePanel({
  selectedShapeId,
  onInjectImage,
  onReplaceHtml,
}: Readonly<ExtensionPanelProps>) {
  const [lastAction, setLastAction] = useState<string | null>(null);

  const handleInjectImage = () => {
    onInjectImage(PLACEHOLDER_SVG);
    setLastAction("Injected placeholder image into the selected shape");
  };

  const handleReplaceHtml = () => {
    onReplaceHtml(PLACEHOLDER_HTML);
    setLastAction("Replaced HTML with generated placeholder content");
  };

  return (
    <div className="space-y-4">
      <div className="rounded-lg border border-zinc-800/70 bg-zinc-900/70 px-3 py-2">
        <span className="text-[11px] text-zinc-400">
          {selectedShapeId
            ? `Selected shape: ${selectedShapeId}`
            : "Select a shape in the canvas"}
        </span>
      </div>

      <div className="space-y-2">
        <button
          onClick={handleInjectImage}
          disabled={!selectedShapeId}
          className="w-full rounded-lg bg-zinc-50 px-3 py-2 text-sm font-medium text-zinc-900 transition-colors hover:bg-white disabled:cursor-not-allowed disabled:bg-zinc-800 disabled:text-zinc-500"
          data-testid="ai-stub-inject-image"
        >
          Inject placeholder image
        </button>

        <button
          onClick={handleReplaceHtml}
          disabled={!selectedShapeId}
          className="w-full rounded-lg border border-zinc-800/70 bg-zinc-950/80 px-3 py-2 text-sm font-medium text-zinc-100 transition-colors hover:bg-white/[0.04] disabled:cursor-not-allowed disabled:text-zinc-500"
          data-testid="ai-stub-replace-html"
        >
          Replace full HTML
        </button>
      </div>

      {lastAction && (
        <p className="text-xs italic text-zinc-500">{lastAction}</p>
      )}

      <div className="space-y-1 rounded-lg border border-zinc-800/70 p-3">
        <p className="text-xs font-medium text-zinc-200">Reference extension</p>
        <p className="text-[11px] leading-relaxed text-zinc-500">
          This is a development stub. It does not connect to a real AI provider.
          It exists to validate the canvas extension pipeline.
        </p>
      </div>
    </div>
  );
}
