/**
 * AI Image Stub — Panel component.
 *
 * Reference extension demonstrating the extension Panel contract.
 * Shows a simple UI with a "Generate" button that injects a placeholder
 * SVG image into the selected shape. No real AI provider integration —
 * this is a development scaffold for testing the extension pipeline.
 */
import { useState } from "react";
import type { ExtensionPanelProps } from "../registry";

/** Placeholder SVG encoded as a data URI — no network request needed. */
const PLACEHOLDER_SVG = `data:image/svg+xml,${encodeURIComponent(
  `<svg xmlns="http://www.w3.org/2000/svg" width="400" height="400" viewBox="0 0 400 400">
    <rect width="400" height="400" fill="#f0f0f0"/>
    <text x="200" y="190" text-anchor="middle" font-family="system-ui" font-size="14" fill="#888">AI Image Placeholder</text>
    <text x="200" y="215" text-anchor="middle" font-family="system-ui" font-size="11" fill="#aaa">Extension stub — no real provider</text>
  </svg>`,
)}`;

/** Placeholder HTML block injected as a new slide. */
const PLACEHOLDER_HTML = `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><style>
  body { margin: 0; display: flex; align-items: center; justify-content: center; min-height: 100vh; background: #fafafa; font-family: system-ui, sans-serif; }
  .card { text-align: center; padding: 2rem; }
  img { width: 100%; max-width: 320px; border-radius: 8px; }
  p { color: #666; font-size: 0.875rem; margin-top: 1rem; }
</style></head>
<body>
  <div class="card">
    <img src="${PLACEHOLDER_SVG}" alt="AI Generated placeholder" />
    <p>Generated by AI Image Stub</p>
  </div>
</body>
</html>`;

export function AiImagePanel({
  selectedShapeId,
  onInjectImage,
  onReplaceHtml,
}: ExtensionPanelProps) {
  const [lastAction, setLastAction] = useState<string | null>(null);

  const handleInjectImage = () => {
    onInjectImage(PLACEHOLDER_SVG);
    setLastAction("Imagen inyectada en el shape seleccionado");
  };

  const handleReplaceHtml = () => {
    onReplaceHtml(PLACEHOLDER_HTML);
    setLastAction("HTML reemplazado con placeholder generado");
  };

  return (
    <div className="space-y-4">
      {/* Status: selected shape */}
      <div className="rounded-md bg-muted px-3 py-2">
        <span className="text-[11px] text-muted-foreground">
          {selectedShapeId
            ? `Shape seleccionado: ${selectedShapeId}`
            : "Seleccioná un shape en el canvas"}
        </span>
      </div>

      {/* Actions */}
      <div className="space-y-2">
        <button
          onClick={handleInjectImage}
          disabled={!selectedShapeId}
          className="w-full px-3 py-2 text-sm font-medium rounded-md bg-primary text-primary-foreground hover:bg-primary/90 disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          data-testid="ai-stub-inject-image"
        >
          Inyectar imagen placeholder
        </button>

        <button
          onClick={handleReplaceHtml}
          disabled={!selectedShapeId}
          className="w-full px-3 py-2 text-sm font-medium rounded-md border border-border bg-background text-foreground hover:bg-accent disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
          data-testid="ai-stub-replace-html"
        >
          Reemplazar HTML completo
        </button>
      </div>

      {/* Feedback */}
      {lastAction && (
        <p className="text-xs text-muted-foreground italic">{lastAction}</p>
      )}

      {/* Info */}
      <div className="rounded-md border border-border p-3 space-y-1">
        <p className="text-xs font-medium text-foreground">
          Extensión de referencia
        </p>
        <p className="text-[11px] text-muted-foreground leading-relaxed">
          Este es un stub de desarrollo. No se conecta a ningún proveedor de IA
          real. Sirve para validar el pipeline de extensiones del canvas.
        </p>
      </div>
    </div>
  );
}
