# Generated by Django 6.0.3 on 2026-04-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_project_color_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="icon_storage_key",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
