# Generated by Django 6.0.3 on 2026-03-23 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("approvals", "0001_initial"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvaldecision",
            name="draft_post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approval_decisions",
                to="posts.draftpost",
            ),
        ),
        migrations.AddField(
            model_name="approvedsnapshot",
            name="approval_decision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="snapshots",
                to="approvals.approvaldecision",
            ),
        ),
        migrations.AddField(
            model_name="approvedsnapshot",
            name="draft_post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="approved_snapshot",
                to="posts.draftpost",
            ),
        ),
    ]
