# Generated by Django 6.0.3 on 2026-03-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("generation", "0002_add_project_and_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="comparerun",
            name="height",
            field=models.PositiveIntegerField(default=1080),
        ),
        migrations.AddField(
            model_name="comparerun",
            name="slide_count",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="comparerun",
            name="width",
            field=models.PositiveIntegerField(default=1080),
        ),
        migrations.AlterField(
            model_name="comparerun",
            name="format",
            field=models.CharField(default="ig_square", max_length=20),
        ),
    ]
