# Generated by Django 6.0.3 on 2026-03-24 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_add_project_format_html"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftvariant",
            name="slide_index",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="draftpost",
            name="format",
            field=models.CharField(blank=True, default="ig_square", max_length=20),
        ),
        migrations.CreateModel(
            name="CarouselSlide",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slide_index", models.PositiveSmallIntegerField()),
                (
                    "draft_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="carousel_slides",
                        to="posts.draftpost",
                    ),
                ),
                (
                    "selected_variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="carousel_selections",
                        to="posts.draftvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["slide_index"],
                "unique_together": {("draft_post", "slide_index")},
            },
        ),
    ]
