# Generated by Django 6.0.3 on 2026-04-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_add_slide_index_carousel_slide_expand_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftvariant",
            name="derived_from_variant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_variants",
                to="posts.draftvariant",
            ),
        ),
        migrations.AddField(
            model_name="draftvariant",
            name="generation_meta",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="draftvariant",
            name="variant_type",
            field=models.CharField(default="default", max_length=20),
        ),
        migrations.CreateModel(
            name="DraftFrameMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slide_index", models.PositiveSmallIntegerField()),
                ("name", models.CharField(blank=True, max_length=255)),
                ("is_favorite", models.BooleanField(default=False)),
                ("annotations", models.JSONField(blank=True, default=list)),
                (
                    "draft_post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="frame_metadata",
                        to="posts.draftpost",
                    ),
                ),
            ],
            options={
                "ordering": ["slide_index"],
                "unique_together": {("draft_post", "slide_index")},
            },
        ),
    ]
