# Generated by Django 6.0.3 on 2026-04-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_schema_strip_publishing"),
    ]

    operations = [
        migrations.AddField(
            model_name="draftpost",
            name="global_styles",
            field=models.TextField(blank=True, default=""),
        ),
    ]
